//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teeths
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.TeethInformations = new HashSet<TeethInformation>();
        }
    
        public int Id { get; set; }
        public string Number { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public string Name { get; set; }
        public string Old { get; set; }
        public Nullable<byte> Sex { get; set; }
        public string Adress { get; set; }
        public string Proffesion { get; set; }
        public string FirstDiagnos { get; set; }
        public string DiseaseInfo { get; set; }
        public string DiseaseNow { get; set; }
    
        public virtual ICollection<TeethInformation> TeethInformations { get; set; }
    }
}
