//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teeths
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataView
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public string DataOuterView { get; set; }
        public string Descriptionbite { get; set; }
        public string Descriptionmucous { get; set; }
        public string DataXray { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
