//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teeths
{
    using System;
    using System.Collections.Generic;
    
    public partial class Everytooth
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public string ViewData { get; set; }
        public string Teeth_number { get; set; }
        public Nullable<byte> O { get; set; }
        public Nullable<byte> R { get; set; }
        public Nullable<byte> C { get; set; }
        public Nullable<byte> P { get; set; }
        public Nullable<byte> Pt { get; set; }
        public Nullable<byte> Pi { get; set; }
        public Nullable<byte> A { get; set; }
        public string Movement { get; set; }
        public Nullable<byte> K { get; set; }
        public Nullable<byte> I { get; set; }
        public string X { get; set; }
        public string Y { get; set; }
        public string Z { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
